### ISSUE TITLE
Reupload

### ISSUE THREAD

**Issue by tsukasaroot** [pjouglet/tera_shock#1]
Hello, it is possible to reupload the client+patch? Link is dead, same for the db+ready server in ragezone.
Hope those files are still somewhere o/
regards

**Comment by pjouglet** [comment]
Hi !
Yes, i still have the client on my computer. I'll need to compress & upload it.
Same for database i have it too

**Comment by tsukasaroot** [comment]
Oh thanks for the fast reply, when you will have time you will be able to upload it back? I would like to make it run and try to work on this emulator to not start from scratch :D

**Comment by pjouglet** [comment]
Yes, of course i can upload it haha
But this is an old emulator, a lot of things are missing and very difficult to add..

**Comment by tsukasaroot** [comment]
Mmh, i have the other one from (p5ylo?) if i remember. It is working, but i have no tools to edit anything rn, saw there was tons of xml and all for this java one so thought it would be easier than messing with hexa and a gameserver that i don't have the source.. :/ Which emu would be the less harder to add/fix etc from your experience? the java or the one from S1project that i got? And maybe i missed some tools, but im reading since 4days all thread i can to gather as much informations i can :sweat:

**Comment by pjouglet** [comment]
It's depend.
If you know how to code, it can be better to use the one from p5yl0. Then you can reverse the reading of .bin file in order to add stuff inside.
Also, this one is better if you want to update it to a more recent version.

In Tera_Shock (java one), you'll need the opcodes for add content (good luck for find them). You may need the decrypted datacenter, but with knowledge you can use a recent one.

btw, i'll upload the game & sql in the next days

**Comment by tsukasaroot** [comment]
Okay thanks! I already started to look at P5yl0 one, i was able to do some changes etc C# isn't that hard. The only thing i still not able to do with this one is the reverse reading, i will try to look into that asap ^^
I will still look at the java one, maybe i will find some contents that i can use in the C# one.

**Comment by JusticeTroll** [comment]
did you ever reupload the client btw? 

Here is a shock link https://mega.nz/#!HvYygT6B!fkRW9Lu2zYSTdpYs5O-UR_mCwlWtcY8o0M7k1o4ZMlA

**Comment by fri0z** [comment]
Hi, who can reupload the client on google drive ?   And the have mega limiting on traffic.
