### ISSUE TITLE
did this can be translate to chinese and repack to game file?

### ISSUE THREAD

**Issue by exe19890522** [pjouglet/tera_shock#2]
did this can be translate to chinese and repack to game file?
i don't know how to repack,many people can't to do it.

**Comment by pjouglet** [comment]
Technically it can.
Depend of  the client you're using.

If you want to use the latest TW client it'll require a lot of work.
If you want to use an old chinese client it'll require work too, but less.

**Comment by exe19890522** [comment]
> Technically it can.
> Depend of the client you're using.
> 
> If you want to use the latest TW client it'll require a lot of work.
> If you want to use an old chinese client it'll require work too, but less.

thank you.
